### ISSUE TITLE
CHCO Data Table Pack 2A

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#17]
Can we double check how the mean and median LOS is being calculated in Table Pack 2A? It seems like we should have better data here and less NaN's, NA's.

**Comment by vtmacox** [comment]
It looks like the CHCO data have quite a few dates where the discharge date is before the admission date (124 out of 165 LOS values are negative in the CHCO test data).   The code is counting the frequency of these DXs but because I convert the LOS to NA, there are no mean or median values for those diagnoses.  

I've added code in that give you the count of how many patients had negative LOS values.
