### ISSUE TITLE
CHCO Med Graphs (4A)

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#19]
For the CHCO Med Graphs (4A) can you help me with the interpretation of the hydromorphone graph - there doesn't appear to be a pectus/spine divide. (Similarly, did only spine kids get morphine sulfate?)

**Comment by vtmacox** [comment]
In general, if data appear to be missing from a figure, it is because they don't exist.  For example, there are no pectus patients in the CHCO test data that got Morphin Sulfate so only the spine patients are plotted.  For the Hydromorphone plot, it looks like there was only 1 patient per procedure who recieved this medication.  Using the legend the left boxplot will always be the first plot, and the right plot will be the second one in the legend.
