### ISSUE TITLE
05242018_Table Updates- Cohort Size

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#3]
Table 1D: Please add explanation to decreased cohort size (109 -> 106) due to invalid (//1900) recorded discharge date.

**Comment by vtmacox** [comment]
I don't think you want this in the code.  The reason being, these numbers will change based on the Database that is being queried.  Depending on when this code is run, these numbers will change unpredictably.

**Comment by SArabUCD** [comment]
Yes, could we get it in markdown text?

**Comment by vtmacox** [comment]
This difference will not perpetuate through the data.  As such you don't want this in the code.  In fact, I'm not sure this will be true when DH runs the code on their actual data.  You will have to see what happens when the data are run.  

Because I won't ever have access to the actual data, you may not know why these discrepancies exist.
